import { CategoryMapping } from '../types';

export const produceItems: CategoryMapping = {
  apple: 'produce',
  banana: 'produce',
  orange: 'produce',
  lettuce: 'produce',
  tomato: 'produce',
  carrot: 'produce',
  potato: 'produce',
  onion: 'produce',
  garlic: 'produce',
  strawberry: 'produce',
  strawberries: 'produce',
  berry: 'produce',
  berries: 'produce',
  grape: 'produce',
  grapes: 'produce',
  lemon: 'produce',
  lime: 'produce',
  avocado: 'produce',
  cucumber: 'produce',
  pepper: 'produce',
  broccoli: 'produce',
  cauliflower: 'produce',
  celery: 'produce',
  spinach: 'produce',
  kale: 'produce',
  mushroom: 'produce',
  mushrooms: 'produce',
  zucchini: 'produce',
  squash: 'produce',
  pear: 'produce',
  peach: 'produce',
  plum: 'produce',
  mango: 'produce',
  pineapple: 'produce',
  melon: 'produce',
  watermelon: 'produce',
  cantaloupe: 'produce',
  asparagus: 'produce',
  eggplant: 'produce',
  cabbage: 'produce',
  radish: 'produce',
  corn: 'produce',
  ginger: 'produce',
  herbs: 'produce',
  basil: 'produce',
  cilantro: 'produce',
  parsley: 'produce',
  mint: 'produce',
  thyme: 'produce',
  rosemary: 'produce',
  sage: 'produce'
} as const;

export const dairyItems: CategoryMapping = {
  milk: 'dairy',
  cheese: 'dairy',
  yogurt: 'dairy',
  butter: 'dairy',
  cream: 'dairy',
  eggs: 'dairy',
  'sour cream': 'dairy',
  'cottage cheese': 'dairy',
  'whipping cream': 'dairy'
} as const;

export const meatItems: CategoryMapping = {
  chicken: 'meat',
  beef: 'meat',
  pork: 'meat',
  fish: 'meat',
  salmon: 'meat',
  turkey: 'meat',
  lamb: 'meat',
  shrimp: 'meat',
  seafood: 'meat',
  steak: 'meat',
  'ground beef': 'meat',
  'ground turkey': 'meat',
  sausage: 'meat',
  bacon: 'meat',
  ham: 'meat',
  tuna: 'meat'
} as const;

export const pantryItems: CategoryMapping = {
  rice: 'pantry',
  pasta: 'pantry',
  bread: 'pantry',
  flour: 'pantry',
  sugar: 'pantry',
  oil: 'pantry',
  cereal: 'pantry',
  spice: 'pantry',
  spices: 'pantry',
  sauce: 'pantry',
  can: 'pantry',
  canned: 'pantry',
  bean: 'pantry',
  beans: 'pantry',
  soup: 'pantry',
  noodle: 'pantry',
  noodles: 'pantry',
  crackers: 'pantry',
  chips: 'pantry',
  snack: 'pantry',
  nuts: 'pantry',
  'peanut butter': 'pantry',
  'almond butter': 'pantry',
  vinegar: 'pantry'
} as const;

export const frozenItems: CategoryMapping = {
  'ice cream': 'frozen',
  'frozen pizza': 'frozen',
  'frozen vegetables': 'frozen',
  frozen: 'frozen',
  popsicle: 'frozen'
} as const;