import { CategoryMapping } from '../types';

export const outdoorItems: CategoryMapping = {
  plant: 'outdoor',
  seed: 'outdoor',
  seeds: 'outdoor',
  fertilizer: 'outdoor',
  soil: 'outdoor',
  mulch: 'outdoor',
  garden: 'outdoor',
  trimmer: 'outdoor',
  mower: 'outdoor',
  rake: 'outdoor',
  shovel: 'outdoor',
  hose: 'outdoor',
  sprinkler: 'outdoor',
  watering: 'outdoor',
  planter: 'outdoor',
  pot: 'outdoor',
  pots: 'outdoor',
  trellis: 'outdoor',
  pruner: 'outdoor',
  shears: 'outdoor',
  'garden gloves': 'outdoor',
  weed: 'outdoor',
  pesticide: 'outdoor',
  insecticide: 'outdoor',
  'outdoor light': 'outdoor',
  'christmas light': 'outdoor',
  landscape: 'outdoor',
  lawn: 'outdoor',
  grass: 'outdoor',
  flower: 'outdoor',
  'plant food': 'outdoor',
  'bird feeder': 'outdoor',
  'bird seed': 'outdoor',
  'outdoor furniture': 'outdoor',
  patio: 'outdoor'
} as const;