// Category types
import { ItemCategory } from '../types/shopping';

// Combine all category mappings
export const itemCategoryMap: Record<string, ItemCategory> = {
  // Produce section
  apple: 'produce',
  banana: 'produce',
  orange: 'produce',
  lettuce: 'produce',
  tomato: 'produce',
  carrot: 'produce',
  potato: 'produce',
  onion: 'produce',
  garlic: 'produce',
  strawberry: 'produce',
  strawberries: 'produce',
  berry: 'produce',
  berries: 'produce',
  grape: 'produce',
  grapes: 'produce',
  lemon: 'produce',
  lime: 'produce',
  avocado: 'produce',
  cucumber: 'produce',
  pepper: 'produce',
  broccoli: 'produce',
  cauliflower: 'produce',
  celery: 'produce',
  spinach: 'produce',
  kale: 'produce',
  mushroom: 'produce',
  mushrooms: 'produce',
  zucchini: 'produce',
  squash: 'produce',
  pear: 'produce',
  peach: 'produce',
  plum: 'produce',
  mango: 'produce',
  pineapple: 'produce',
  melon: 'produce',
  watermelon: 'produce',
  cantaloupe: 'produce',
  asparagus: 'produce',
  eggplant: 'produce',
  cabbage: 'produce',
  radish: 'produce',
  corn: 'produce',
  ginger: 'produce',
  herbs: 'produce',
  basil: 'produce',
  cilantro: 'produce',
  parsley: 'produce',
  mint: 'produce',
  thyme: 'produce',
  rosemary: 'produce',
  sage: 'produce',

  // Dairy section
  milk: 'dairy',
  cheese: 'dairy',
  yogurt: 'dairy',
  butter: 'dairy',
  cream: 'dairy',
  eggs: 'dairy',
  'sour cream': 'dairy',
  'cottage cheese': 'dairy',
  'whipping cream': 'dairy',

  // Meat section
  chicken: 'meat',
  beef: 'meat',
  pork: 'meat',
  fish: 'meat',
  salmon: 'meat',
  turkey: 'meat',
  lamb: 'meat',
  shrimp: 'meat',
  seafood: 'meat',
  steak: 'meat',
  'ground beef': 'meat',
  'ground turkey': 'meat',
  sausage: 'meat',
  bacon: 'meat',
  ham: 'meat',
  tuna: 'meat',

  // Pantry section
  rice: 'pantry',
  pasta: 'pantry',
  bread: 'pantry',
  flour: 'pantry',
  sugar: 'pantry',
  oil: 'pantry',
  cereal: 'pantry',
  spice: 'pantry',
  spices: 'pantry',
  sauce: 'pantry',
  can: 'pantry',
  canned: 'pantry',
  bean: 'pantry',
  beans: 'pantry',
  soup: 'pantry',
  noodle: 'pantry',
  noodles: 'pantry',
  crackers: 'pantry',
  chips: 'pantry',
  snack: 'pantry',
  nuts: 'pantry',
  'peanut butter': 'pantry',
  'almond butter': 'pantry',
  vinegar: 'pantry',

  // Frozen section
  'ice cream': 'frozen',
  'frozen pizza': 'frozen',
  'frozen vegetables': 'frozen',
  frozen: 'frozen',
  popsicle: 'frozen',

  // Beverages
  water: 'beverages',
  soda: 'beverages',
  juice: 'beverages',
  coffee: 'beverages',
  tea: 'beverages',
  drink: 'beverages',
  beer: 'beverages',
  wine: 'beverages',
  'almond milk': 'beverages',
  'soy milk': 'beverages',

  // Household section
  'paper towels': 'household',
  'toilet paper': 'household',
  soap: 'household',
  detergent: 'household',
  cleaner: 'household',
  cleaning: 'household',
  trash: 'household',
  garbage: 'household',
  bags: 'household',
  sponge: 'household',
  napkins: 'household',
  foil: 'household',
  wrap: 'household',
  battery: 'household',
  batteries: 'household',
  'light bulb': 'household',

  // Toiletries section
  shampoo: 'toiletries',
  toothpaste: 'toiletries',
  deodorant: 'toiletries',
  'dental floss': 'toiletries',
  'hand soap': 'toiletries',
  'body wash': 'toiletries',
  'face wash': 'toiletries',
  lotion: 'toiletries',
  'hand cream': 'toiletries',
  'hair conditioner': 'toiletries',
  'mouth wash': 'toiletries',
  'tooth brush': 'toiletries',
  razor: 'toiletries',
  'shaving cream': 'toiletries',
  tissue: 'toiletries',
  tissues: 'toiletries',
  'cotton balls': 'toiletries',
  'cotton swabs': 'toiletries',
  sunscreen: 'toiletries',
  moisturizer: 'toiletries',
  makeup: 'toiletries',
  'feminine products': 'toiletries',
  bandage: 'toiletries',
  bandages: 'toiletries',
  'first aid': 'toiletries',

  // Baby section
  diaper: 'baby',
  diapers: 'baby',
  wipes: 'baby',
  formula: 'baby',
  bottle: 'baby',
  bottles: 'baby',
  binky: 'baby',
  pacifier: 'baby',
  'baby food': 'baby',
  'baby clothes': 'baby',
  'baby lotion': 'baby',
  'baby shampoo': 'baby',
  'baby wash': 'baby',
  'baby powder': 'baby',
  'baby oil': 'baby',
  'diaper rash cream': 'baby',
  'baby monitor': 'baby',
  teething: 'baby',
  bib: 'baby',
  bibs: 'baby',
  stroller: 'baby',
  crib: 'baby',

  // Pet section
  'dog food': 'pet',
  'cat food': 'pet',
  'pet food': 'pet',
  'flea treatment': 'pet',
  'heartworm medicine': 'pet',
  'pet treats': 'pet',
  'cat litter': 'pet',
  'dog treats': 'pet',
  'cat treats': 'pet',
  'pet toy': 'pet',
  'dog toy': 'pet',
  'cat toy': 'pet',
  leash: 'pet',
  collar: 'pet',
  'pet bed': 'pet',
  'pet shampoo': 'pet',
  'pet brush': 'pet',
  'pet medicine': 'pet',
  veterinary: 'pet',

  // Clothing section
  shirt: 'clothing',
  pants: 'clothing',
  shorts: 'clothing',
  dress: 'clothing',
  skirt: 'clothing',
  underwear: 'clothing',
  socks: 'clothing',
  hat: 'clothing',
  cap: 'clothing',
  sunglasses: 'clothing',
  shoes: 'clothing',
  boots: 'clothing',
  sandals: 'clothing',
  jacket: 'clothing',
  coat: 'clothing',
  sweater: 'clothing',
  'winter gloves': 'clothing',
  scarf: 'clothing',
  belt: 'clothing',
  tie: 'clothing',

  // Electronics section
  'surge protector': 'electronics',
  'charging cable': 'electronics',
  charger: 'electronics',
  cable: 'electronics',
  tv: 'electronics',
  television: 'electronics',
  computer: 'electronics',
  laptop: 'electronics',
  phone: 'electronics',
  tablet: 'electronics',
  headphones: 'electronics',
  earbuds: 'electronics',
  speaker: 'electronics',
  camera: 'electronics',
  router: 'electronics',
  keyboard: 'electronics',
  mouse: 'electronics',
  monitor: 'electronics',
  printer: 'electronics',
  'usb drive': 'electronics',
  'memory card': 'electronics',
  'hard drive': 'electronics',

  // Nutrition section
  'protein powder': 'nutrition',
  protein: 'nutrition',
  creatine: 'nutrition',
  'pre workout': 'nutrition',
  preworkout: 'nutrition',
  'post workout': 'nutrition',
  vitamins: 'nutrition',
  vitamin: 'nutrition',
  supplement: 'nutrition',
  supplements: 'nutrition',
  melatonin: 'nutrition',
  'fish oil': 'nutrition',
  'omega 3': 'nutrition',
  'protein bar': 'nutrition',
  'protein bars': 'nutrition',
  'energy bar': 'nutrition',
  'energy bars': 'nutrition',
  'protein shake': 'nutrition',
  'meal replacement': 'nutrition',
  bcaa: 'nutrition',
  'amino acids': 'nutrition',

  // Outdoor section
  plant: 'outdoor',
  seed: 'outdoor',
  seeds: 'outdoor',
  fertilizer: 'outdoor',
  soil: 'outdoor',
  mulch: 'outdoor',
  garden: 'outdoor',
  trimmer: 'outdoor',
  mower: 'outdoor',
  rake: 'outdoor',
  shovel: 'outdoor',
  hose: 'outdoor',
  sprinkler: 'outdoor',
  watering: 'outdoor',
  planter: 'outdoor',
  pot: 'outdoor',
  pots: 'outdoor',
  trellis: 'outdoor',
  pruner: 'outdoor',
  shears: 'outdoor',
  'garden gloves': 'outdoor',
  weed: 'outdoor',
  pesticide: 'outdoor',
  insecticide: 'outdoor',
  'outdoor light': 'outdoor',
  'christmas light': 'outdoor',
  landscape: 'outdoor',
  lawn: 'outdoor',
  grass: 'outdoor',
  flower: 'outdoor',
  'plant food': 'outdoor',
  'bird feeder': 'outdoor',
  'bird seed': 'outdoor',
  'outdoor furniture': 'outdoor',
  patio: 'outdoor'
};

export function categorizeItem(itemName: string): ItemCategory {
  const normalizedName = itemName.toLowerCase().trim();
  
  // Check for exact matches
  if (itemCategoryMap[normalizedName]) {
    return itemCategoryMap[normalizedName];
  }

  // Check for partial matches
  for (const [key, category] of Object.entries(itemCategoryMap)) {
    if (normalizedName.includes(key)) {
      return category;
    }
  }

  return 'other';
}

export const categoryIcons: Record<ItemCategory, string> = {
  produce: '🥬',
  dairy: '🥛',
  meat: '🥩',
  pantry: '🥫',
  frozen: '❄️',
  beverages: '🥤',
  household: '🏠',
  toiletries: '🧴',
  baby: '👶',
  pet: '🐾',
  clothing: '👕',
  electronics: '🔌',
  nutrition: '💪',
  outdoor: '🌿',
  other: '📦'
};

export const categoryNames: Record<ItemCategory, string> = {
  produce: 'Produce',
  dairy: 'Dairy',
  meat: 'Meat & Seafood',
  pantry: 'Pantry',
  frozen: 'Frozen',
  beverages: 'Beverages',
  household: 'Household',
  toiletries: 'Toiletries',
  baby: 'Baby',
  pet: 'Pet Supplies',
  clothing: 'Clothing',
  electronics: 'Electronics',
  nutrition: 'Nutrition & Supplements',
  outdoor: 'Outdoor & Garden',
  other: 'Other'
};